menu:
- {name: 'publications', url: '/publications'}
- {name: 'courses', url: '/courses'}
- {name: 'resume', url: '/resume'}
- {name: 'contact', url: '/contact'}

courses:
- {name: 'Vector Calculus', url: 'vector-calculus'}
- {name: 'Quantum Mechanics', url: 'quantum-mechanics'}
- {name: 'Stellar Structures', url: 'stellar-structures'}

social:
- {icon: 'github', link: 'https://github.com/sgx718'}
- {icon: 'linkedin', link: 'https://linkedin.com/in/samgoers'}

contacts:
- {name: 'Sam Goers', title: 'Student', department: 'College of Engineering', institution: 'The Unviersity of Georgia', institution_address: 'Athens, GA', phone: '(470) 548-8852', email: 'samgoers@outlook.com'}
